// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVKXQwtr67pWELM8yROALTulpKlA-ccAg',
    appId: '1:691828105579:web:adb077791346d73870ac2e',
    messagingSenderId: '691828105579',
    projectId: 'hypeneedz-8cb89',
    authDomain: 'hypeneedz-8cb89.firebaseapp.com',
    storageBucket: 'hypeneedz-8cb89.appspot.com',
    measurementId: 'G-H7BHSNWS97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEoTaK2CIU98EX4f37LSTqwv6Ne0K4cEw',
    appId: '1:691828105579:android:53fb0604bd9d9a4e70ac2e',
    messagingSenderId: '691828105579',
    projectId: 'hypeneedz-8cb89',
    storageBucket: 'hypeneedz-8cb89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_j0-1VT0EQLnRLWJZ3X1lZG1P7YI8DAc',
    appId: '1:691828105579:ios:1bfbf68fde60f3c570ac2e',
    messagingSenderId: '691828105579',
    projectId: 'hypeneedz-8cb89',
    storageBucket: 'hypeneedz-8cb89.appspot.com',
    iosClientId: '691828105579-nnespldrla1v3krq6deshahbbm5rfa69.apps.googleusercontent.com',
    iosBundleId: 'com.example.hypeneedz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_j0-1VT0EQLnRLWJZ3X1lZG1P7YI8DAc',
    appId: '1:691828105579:ios:1bfbf68fde60f3c570ac2e',
    messagingSenderId: '691828105579',
    projectId: 'hypeneedz-8cb89',
    storageBucket: 'hypeneedz-8cb89.appspot.com',
    iosClientId: '691828105579-nnespldrla1v3krq6deshahbbm5rfa69.apps.googleusercontent.com',
    iosBundleId: 'com.example.hypeneedz',
  );
}
